# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Geological_Structure_Analysis.py
# Created on: 2020-01-14 07:51:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Geological_Structure_Analysis <Structure_Pt> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Structure_Pt = arcpy.GetParameterAsText(0)

# Local variables:
Structure_Direction_Reelle_1 = ""
Structure_Direction_Reelle_2 = ""
Structure_Direction_Reelle_Merge = "D:\\Managem\\TriK_2019\\Orpaillage\\Output\\Output.gdb\\Merge"
Structure_Direction_Reelle_shp = "D:\\Managem\\TriK_2019\\Hassan\\Exploration_2019\\Structure\\Structure_Direction_Reelle.shp"
Structure_Pendage_Reelle = "D:\\Managem\\TriK_2019\\Hassan\\Exploration_2019\\Structure\\Structure_Pendage_Reelle.shp"
Structure_Direction_Visible_1 = ""
Structure_Direction_Visible_2 = ""
Structure_Direction_Visible_Merge = "D:\\Managem\\TriK_2019\\Orpaillage\\Output\\Output.gdb\\Merge1"
Structure_Direction_Visible_shp = "D:\\Managem\\TriK_2019\\Hassan\\Exploration_2019\\Structure\\Structure_Direction_Visible.shp"
Structure_Pendage_Visible = "D:\\Managem\\TriK_2019\\Hassan\\Exploration_2019\\Structure\\Structure_Pendage_Visible.shp"

# Process: Bearing Direction Reelle +
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Direction_Reelle_1, "X_UTM", "Y_UTM", "Longueur", "9001", "Strike", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

# Process: Bearing Direction Reelle -
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Direction_Reelle_2, "X_UTM", "Y_UTM", "Long_Comp", "9001", "Strike", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

# Process: Merge Direction Reelle
arcpy.Merge_management("'';''", Structure_Direction_Reelle_Merge, "Identifer \"Identifer\" true true false 0 Text 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Identifer,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Identifer,-1,-1;X_UTM \"X_UTM\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,X_UTM,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,X_UTM,-1,-1;Y_UTM \"Y_UTM\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Y_UTM,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Y_UTM,-1,-1;Longueur \"Longueur\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Longueur,-1,-1;Strike \"Strike\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Strike,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Strike,-1,-1;Long_Comp \"Long_Comp\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Long_Comp,-1,-1")

# Process: Dissolve Direction Reelle
arcpy.Dissolve_management(Structure_Direction_Reelle_Merge, Structure_Direction_Reelle_shp, "Identifer", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Bearing Pendage Reelle
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Pendage_Reelle, "X_UTM", "Y_UTM", "L_Pd_Dir", "9001", "Pd_Dir", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

# Process: Bearing Direction Visible +
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Direction_Visible_1, "X_UTM", "Y_UTM", "Long_Vue", "9001", "Strike", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

# Process: Bearing Direction Visible -
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Direction_Visible_2, "X_UTM", "Y_UTM", "Long_C_Vue", "9001", "Strike", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

# Process: Merge Direction Visible
arcpy.Merge_management("'';''", Structure_Direction_Visible_Merge, "Identifer \"Identifer\" true true false 0 Text 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Identifer,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Identifer,-1,-1;X_UTM \"X_UTM\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,X_UTM,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,X_UTM,-1,-1;Y_UTM \"Y_UTM\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Y_UTM,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Y_UTM,-1,-1;Longueur \"Longueur\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Longueur,-1,-1;Strike \"Strike\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Strike,-1,-1,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Strike,-1,-1;Long_Comp \"Long_Comp\" true true false 0 Double 0 0 ,First,#,D:\\Managem\\TriK_2019\\Hassan\\Cartographie.gdb\\Structure_Pt_BearingDistance,Long_Comp,-1,-1")

# Process: Dissolve Direction Visible
arcpy.Dissolve_management(Structure_Direction_Visible_Merge, Structure_Direction_Visible_shp, "Identifer", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Bearing Pendage Visible
arcpy.BearingDistanceToLine_management(Structure_Pt, Structure_Pendage_Visible, "X_UTM", "Y_UTM", "L_P_D_Vue", "9001", "Pd_Dir", "9102", "0", "Identifer", "PROJCS['WGS_1984_UTM_Zone_29N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-9.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 450445547.391054;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

